# Generated by Django 3.2.7 on 2021-09-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateTimeField()),
            ],
        ),
    ]
